language: R
cache: packages
warnings_are_errors: true
sudo: false

matrix:
  include:
    - os: linux
      r: release
    
    - os: linux
      r: devel
      
    - os: osx
      r: release
      before_install:
        - brew update
        - brew install llvm
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

      
    - os: osx
      r: devel
      before_install:
        - brew update
        - brew install llvm
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

r_github_packages:
- hadley/scales
- hadley/ggplot2

r_packages:
- fastcluster
- reshape2
- Rcpp
- RcppArmadillo
- gplots
- pheatmap
- ellipse
- truncnorm
- tibble
- lazyeval
- foreach
- doParallel
- itertools
- microbenchmark
- viridis

r_check_args: "--as-cran --timings"
