language: R
cache: packages
warnings_are_errors: true
sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
    
    - os: linux
      dist: trusty
      r: devel
      
  allow_failures:
    - os: osx
      r: release

    - os: osx
      r: devel

r_github_packages:
- hadley/scales
- hadley/ggplot2

r_packages:
- fastcluster
- reshape2
- Rcpp
- RcppArmadillo
- gplots
- pheatmap
- ellipse
- truncnorm
- tibble
- lazyeval
- foreach
- doParallel
- itertools
- microbenchmark
- viridis

r_check_args: "--as-cran --timings"
