language: R
cache: packages
warnings_are_errors: true
sudo: false

r: 
- release
- devel

os:
- linux
- osx:
  osx_image: xcode9

r_github_packages:
- hadley/scales
- hadley/ggplot2

r_packages:
- fastcluster
- reshape2
- Rcpp
- RcppArmadillo
- gplots
- pheatmap
- ellipse
- truncnorm
- tibble
- lazyeval
- foreach
- doParallel
- itertools
- microbenchmark
- viridis

r_check_args: "--as-cran --timings"
