language: R
cache: packages
warnings_are_errors: true
sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
    
    - os: linux
      dist: trusty
      r: devel
      
    - os: osx
      r: devel

allow_failures:
    - os: osx
      r: release

r_packages:
- Rcpp
- RcppArmadillo
- fastcluster
- reshape2
- gplots
- pheatmap
- ellipse
- truncnorm
- tibble
- lazyeval
- foreach
- doParallel
- itertools
- microbenchmark
- viridis

r_github_packages:
- hadley/scales
- hadley/ggplot2
- jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(type ="all")'

r_check_args: "--as-cran --timings"
