language: R
cache: packages
warnings_are_errors: true
sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
    
    - os: linux
      dist: trusty
      r: devel
      
    - os: osx
      r: devel
      
    - os: osx
      r: release

before_deploy:
  # so no overwrite of linux build
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
  
r_github_packages:
- hadley/scales
- hadley/ggplot2
- jimhester/covr

r_packages:
- fastcluster
- reshape2
- Rcpp
- RcppArmadillo
- gplots
- pheatmap
- ellipse
- truncnorm
- tibble
- lazyeval
- foreach
- doParallel
- itertools
- microbenchmark
- viridis

after_success:
  - Rscript -e 'covr::codecov(type ="all")'

r_check_args: "--as-cran --timings"
