language: R
cache: packages
warnings_are_errors: true
sudo: true

matrix:
  include:
    - os: linux
      r: release
    
    - os: linux
      r: devel
      
    - os: osx
      osx_image: xcode9
      r: release
      env:
        - MATRIX_EVAL="brew update && brew install --with-toolchain llvm && CC=clang-4.0 && CXX=clang++-4.0"
      before_install:
        - eval "${MATRIX_EVAL}"
      
    - os: osx
      r: devel

r_github_packages:
- hadley/scales
- hadley/ggplot2

r_packages:
- fastcluster
- reshape2
- Rcpp
- RcppArmadillo
- gplots
- pheatmap
- ellipse
- truncnorm
- tibble
- lazyeval
- foreach
- doParallel
- itertools
- microbenchmark
- viridis

r_check_args: "--as-cran --timings"
